//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickTrader.BotTerminal.Resx.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class gui {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal gui() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TickTrader.BotTerminal.Resx.Locales.gui", typeof(gui).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Candle##.
        /// </summary>
        internal static string ChartType_Candle {
            get {
                return ResourceManager.GetString("ChartType_Candle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Digital Line##.
        /// </summary>
        internal static string ChartType_DigitalLine {
            get {
                return ResourceManager.GetString("ChartType_DigitalLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Digital Mountain##.
        /// </summary>
        internal static string ChartType_DigitalMountain {
            get {
                return ResourceManager.GetString("ChartType_DigitalMountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Line##.
        /// </summary>
        internal static string ChartType_Line {
            get {
                return ResourceManager.GetString("ChartType_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Mountain##.
        /// </summary>
        internal static string ChartType_Mountain {
            get {
                return ResourceManager.GetString("ChartType_Mountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##OHLC##.
        /// </summary>
        internal static string ChartType_OHLC {
            get {
                return ResourceManager.GetString("ChartType_OHLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Scatter##.
        /// </summary>
        internal static string ChartType_Scatter {
            get {
                return ResourceManager.GetString("ChartType_Scatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EMPTY#.
        /// </summary>
        internal static string ConnectionErrorCode_BlockedAccount {
            get {
                return ResourceManager.GetString("ConnectionErrorCode_BlockedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EMPTY#.
        /// </summary>
        internal static string ConnectionErrorCode_InvalidCredentials {
            get {
                return ResourceManager.GetString("ConnectionErrorCode_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EMPTY#.
        /// </summary>
        internal static string ConnectionErrorCode_LoginDeleted {
            get {
                return ResourceManager.GetString("ConnectionErrorCode_LoginDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EMPTY#.
        /// </summary>
        internal static string ConnectionErrorCode_NetworkError {
            get {
                return ResourceManager.GetString("ConnectionErrorCode_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EMPTY#.
        /// </summary>
        internal static string ConnectionErrorCode_ServerError {
            get {
                return ResourceManager.GetString("ConnectionErrorCode_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EMPTY#.
        /// </summary>
        internal static string ConnectionErrorCode_ServerLogout {
            get {
                return ResourceManager.GetString("ConnectionErrorCode_ServerLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EMPTY#.
        /// </summary>
        internal static string ConnectionErrorCode_SlowConnection {
            get {
                return ResourceManager.GetString("ConnectionErrorCode_SlowConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EMPTY#.
        /// </summary>
        internal static string ConnectionErrorCode_Timeout {
            get {
                return ResourceManager.GetString("ConnectionErrorCode_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EMPTY#.
        /// </summary>
        internal static string ConnectionErrorCode_Unknown {
            get {
                return ResourceManager.GetString("ConnectionErrorCode_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Chart Type##.
        /// </summary>
        internal static string ContextMenu_ChartType {
            get {
                return ResourceManager.GetString("ContextMenu_ChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Indicators##.
        /// </summary>
        internal static string ContextMenu_Indicators {
            get {
                return ResourceManager.GetString("ContextMenu_Indicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##New Chart##.
        /// </summary>
        internal static string ContextMenu_NewChart {
            get {
                return ResourceManager.GetString("ContextMenu_NewChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Open Order##.
        /// </summary>
        internal static string ContextMenu_OpenOrder {
            get {
                return ResourceManager.GetString("ContextMenu_OpenOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Periods##.
        /// </summary>
        internal static string ContextMenu_Periods {
            get {
                return ResourceManager.GetString("ContextMenu_Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Timeline##.
        /// </summary>
        internal static string ContextMenu_Timeline {
            get {
                return ResourceManager.GetString("ContextMenu_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##DownloadingTradeHistoryError##.
        /// </summary>
        internal static string DownloadingTradeHistoryError {
            get {
                return ResourceManager.GetString("DownloadingTradeHistoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #JournalMessage#.
        /// </summary>
        internal static string Journal_Message {
            get {
                return ResourceManager.GetString("Journal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #JournalTime#.
        /// </summary>
        internal static string Journal_Time {
            get {
                return ResourceManager.GetString("Journal_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##About##.
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##BotTrader##.
        /// </summary>
        internal static string Menu_BotTrader {
            get {
                return ResourceManager.GetString("Menu_BotTrader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Exit##.
        /// </summary>
        internal static string Menu_ExitBotTrader {
            get {
                return ResourceManager.GetString("Menu_ExitBotTrader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Help##.
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Language##.
        /// </summary>
        internal static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##LoadProfile##.
        /// </summary>
        internal static string Menu_LoadProfile {
            get {
                return ResourceManager.GetString("Menu_LoadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Log In##.
        /// </summary>
        internal static string Menu_LogIn {
            get {
                return ResourceManager.GetString("Menu_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Log Out##.
        /// </summary>
        internal static string Menu_LogOut {
            get {
                return ResourceManager.GetString("Menu_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Manage accounts##.
        /// </summary>
        internal static string Menu_ManageAccounts {
            get {
                return ResourceManager.GetString("Menu_ManageAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##New Chart##.
        /// </summary>
        internal static string Menu_NewChart {
            get {
                return ResourceManager.GetString("Menu_NewChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##New Order##.
        /// </summary>
        internal static string Menu_NewOrder {
            get {
                return ResourceManager.GetString("Menu_NewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Preferences##.
        /// </summary>
        internal static string Menu_Preferences {
            get {
                return ResourceManager.GetString("Menu_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Profile##.
        /// </summary>
        internal static string Menu_Profile {
            get {
                return ResourceManager.GetString("Menu_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##SaveProfile##.
        /// </summary>
        internal static string Menu_SaveProfile {
            get {
                return ResourceManager.GetString("Menu_SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Theme##.
        /// </summary>
        internal static string Menu_Theme {
            get {
                return ResourceManager.GetString("Menu_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Amount##.
        /// </summary>
        internal static string Order_Amount {
            get {
                return ResourceManager.GetString("Order_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Order type##.
        /// </summary>
        internal static string Order_OrderType {
            get {
                return ResourceManager.GetString("Order_OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Price##.
        /// </summary>
        internal static string Order_Price {
            get {
                return ResourceManager.GetString("Order_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Side##.
        /// </summary>
        internal static string Order_Side {
            get {
                return ResourceManager.GetString("Order_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Order_StopPrice##.
        /// </summary>
        internal static string Order_StopPrice {
            get {
                return ResourceManager.GetString("Order_StopPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Symbol##.
        /// </summary>
        internal static string Order_Symbol {
            get {
                return ResourceManager.GetString("Order_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Volume##.
        /// </summary>
        internal static string Order_Volume {
            get {
                return ResourceManager.GetString("Order_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Open order##.
        /// </summary>
        internal static string OrderDialog_Title {
            get {
                return ResourceManager.GetString("OrderDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Amount##.
        /// </summary>
        internal static string Position_Amount {
            get {
                return ResourceManager.GetString("Position_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Side##.
        /// </summary>
        internal static string Position_Side {
            get {
                return ResourceManager.GetString("Position_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Symbol##.
        /// </summary>
        internal static string Position_Symbol {
            get {
                return ResourceManager.GetString("Position_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Buy##.
        /// </summary>
        internal static string SymbolDetails_Buy {
            get {
                return ResourceManager.GetString("SymbolDetails_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Sell##.
        /// </summary>
        internal static string SymbolDetails_Sell {
            get {
                return ResourceManager.GetString("SymbolDetails_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Tab_Algo##.
        /// </summary>
        internal static string Tab_Algo {
            get {
                return ResourceManager.GetString("Tab_Algo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Tab_Assets##.
        /// </summary>
        internal static string Tab_Assets {
            get {
                return ResourceManager.GetString("Tab_Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Tab_BotJournal##.
        /// </summary>
        internal static string Tab_BotJournal {
            get {
                return ResourceManager.GetString("Tab_BotJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Tab_Bots##.
        /// </summary>
        internal static string Tab_Bots {
            get {
                return ResourceManager.GetString("Tab_Bots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Tab_History##.
        /// </summary>
        internal static string Tab_History {
            get {
                return ResourceManager.GetString("Tab_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Tab_Journal##.
        /// </summary>
        internal static string Tab_Journal {
            get {
                return ResourceManager.GetString("Tab_Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Tab_Orders##.
        /// </summary>
        internal static string Tab_Orders {
            get {
                return ResourceManager.GetString("Tab_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Tab_Positions##.
        /// </summary>
        internal static string Tab_Positions {
            get {
                return ResourceManager.GetString("Tab_Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Tab_Symbols##.
        /// </summary>
        internal static string Tab_Symbols {
            get {
                return ResourceManager.GetString("Tab_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Tab_Trade##.
        /// </summary>
        internal static string Tab_Trade {
            get {
                return ResourceManager.GetString("Tab_Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Theme_Dark##.
        /// </summary>
        internal static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Theme_Light##.
        /// </summary>
        internal static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TimelineType_Real##.
        /// </summary>
        internal static string TimelineType_Real {
            get {
                return ResourceManager.GetString("TimelineType_Real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TimelineType_Uniform##.
        /// </summary>
        internal static string TimelineType_Uniform {
            get {
                return ResourceManager.GetString("TimelineType_Uniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TimePeriod_All##.
        /// </summary>
        internal static string TimePeriod_All {
            get {
                return ResourceManager.GetString("TimePeriod_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TimePeriod_CurrentMonth##.
        /// </summary>
        internal static string TimePeriod_CurrentMonth {
            get {
                return ResourceManager.GetString("TimePeriod_CurrentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TradePeriod_Custom##.
        /// </summary>
        internal static string TimePeriod_Custom {
            get {
                return ResourceManager.GetString("TimePeriod_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TimePeriod_LastHour##.
        /// </summary>
        internal static string TimePeriod_LastHour {
            get {
                return ResourceManager.GetString("TimePeriod_LastHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TradePeriod_LastSixMonths##.
        /// </summary>
        internal static string TimePeriod_LastSixMonths {
            get {
                return ResourceManager.GetString("TimePeriod_LastSixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TradePeriod_LastThreeMonths##.
        /// </summary>
        internal static string TimePeriod_LastThreeMonths {
            get {
                return ResourceManager.GetString("TimePeriod_LastThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TradePeriod_LastYear##.
        /// </summary>
        internal static string TimePeriod_LastYear {
            get {
                return ResourceManager.GetString("TimePeriod_LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TimePeriod_PreviousMonth##.
        /// </summary>
        internal static string TimePeriod_PreviousMonth {
            get {
                return ResourceManager.GetString("TimePeriod_PreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TimePeriod_Today##.
        /// </summary>
        internal static string TimePeriod_Today {
            get {
                return ResourceManager.GetString("TimePeriod_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TimePeriod_Yesterday##.
        /// </summary>
        internal static string TimePeriod_Yesterday {
            get {
                return ResourceManager.GetString("TimePeriod_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TradeDirection_All##.
        /// </summary>
        internal static string TradeDirection_All {
            get {
                return ResourceManager.GetString("TradeDirection_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TradeDirection_Buy##.
        /// </summary>
        internal static string TradeDirection_Buy {
            get {
                return ResourceManager.GetString("TradeDirection_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TradeDirection_Buy##.
        /// </summary>
        internal static string TradeDirection_Sell {
            get {
                return ResourceManager.GetString("TradeDirection_Sell", resourceCulture);
            }
        }
    }
}
